workflows:
  android-workflow:
    name: SiteNative Android Workflow
    max_build_duration: 30
    environment:
      vars:
        FCI_KEYSTORE_PATH: /tmp/keystore.keystore
        FCI_KEYSTORE: /signs/test.jks
        FCI_KEYSTORE_PASSWORD: password
        FCI_KEY_PASSWORD: password
        FCI_KEY_ALIAS: test
        PACKAGE_NAME: "io.sitenative.app.prod_app"
        APP_UID: "test_uid"

    scripts:
      - name: Set up key properties
        script: |
          echo $FCI_KEYSTORE | base64 --decode > /tmp/keystore.keystore
          cat >> "$FCI_BUILD_DIR/android/key.properties" <<EOF
          storePassword=$FCI_KEYSTORE_PASSWORD
          keyPassword=$FCI_KEY_PASSWORD
          keyAlias=$FCI_KEY_ALIAS
          storeFile=/tmp/keystore.keystore
          EOF

      - name: Clean previous builds
        script: ./gradlew clean

      - name: Build Release APK
        script: ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/apk/release/app-release.apk
      - app/build/outputs/mapping/release/mapping.txt